// <autogenerated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
using ConductorSharp.Engine.Model;
using ConductorSharp.Engine.Util;
using MediatR;
using Newtonsoft.Json;
using ConductorSharp.Engine.Builders;

namespace ConductorSharp.ScaffoldedDefinitions.Workflows
{
    public partial class NotificationSendToCustomerV1Input : IRequest<NotificationSendToCustomerV1Output>
    {
        /// <originalName>
        /// customer_id
        /// </originalName>
        /// <summary>
        ///  (optional)
        /// </summary>
        /// <remark>
        /// Example: ""
        /// </remark>
        [JsonProperty("customer_id")]
        public dynamic CustomerId { get; set; }

        /// <originalName>
        /// task_to_execute
        /// </originalName>
        /// <summary>
        ///  (optional)
        /// </summary>
        /// <remark>
        /// Example: ""
        /// </remark>
        [JsonProperty("task_to_execute")]
        public dynamic TaskToExecute { get; set; }
    }

    public partial class NotificationSendToCustomerV1Output
    {
    }

    /// <summary>
    /// 
    /// </summary>
    /// <originalName>
    /// NOTIFICATION_send_to_customer
    /// </originalName>
    /// <ownerApp>
    /// 
    /// </ownerApp>
    /// <ownerEmail>
    /// example@example.local
    /// </ownerEmail>
    /// <note>
    /// 
    /// </note>
    [OriginalName("NOTIFICATION_send_to_customer")]
    [Version(1)]
    public partial class NotificationSendToCustomerV1 : SubWorkflowTaskModel<NotificationSendToCustomerV1Input, NotificationSendToCustomerV1Output>
    {
    }
}