// <autogenerated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
using ConductorSharp.Engine.Model;
using ConductorSharp.Engine.Util;
using MediatR;
using Newtonsoft.Json;
using ConductorSharp.Engine.Builders;

namespace ConductorSharp.ScaffoldedDefinitions.Workflows
{
    public partial class NotificationHandleFailureV1Input : IRequest<NotificationHandleFailureV1Output>
    {
        /// <originalName>
        /// workflow_id
        /// </originalName>
        /// <summary>
        ///  (optional)
        /// </summary>
        /// <remark>
        /// Example: ""
        /// </remark>
        [JsonProperty("workflow_id")]
        public dynamic WorkflowId { get; set; }
    }

    public partial class NotificationHandleFailureV1Output
    {
    }

    /// <summary>
    /// 
    /// </summary>
    /// <originalName>
    /// NOTIFICATION_handle_failure
    /// </originalName>
    /// <ownerApp>
    /// 
    /// </ownerApp>
    /// <ownerEmail>
    /// example@example.local
    /// </ownerEmail>
    /// <note>
    /// 
    /// </note>
    [OriginalName("NOTIFICATION_handle_failure")]
    [Version(1)]
    public partial class NotificationHandleFailureV1 : SubWorkflowTaskModel<NotificationHandleFailureV1Input, NotificationHandleFailureV1Output>
    {
    }
}