// <autogenerated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
using ConductorSharp.Engine.Model;
using ConductorSharp.Engine.Util;
using MediatR;
using Newtonsoft.Json;
using ConductorSharp.Engine.Builders;

namespace ConductorSharp.ScaffoldedDefinitions.Tasks
{
    public partial class CustomerGetInput : IRequest<CustomerGetOutput>
    {
        /// <originalName>
        /// customer_id
        /// </originalName>
        [JsonProperty("customer_id")]
        public dynamic CustomerId { get; set; }
    }

    public partial class CustomerGetOutput
    {
        /// <originalName>
        /// name
        /// </originalName>
        [JsonProperty("name")]
        public dynamic Name { get; set; }

        /// <originalName>
        /// address
        /// </originalName>
        [JsonProperty("address")]
        public dynamic Address { get; set; }
    }

    /// <originalName>
    /// CUSTOMER_get
    /// </originalName>
    /// <ownerEmail>
    /// undefined@undefined.local
    /// </ownerEmail>
    /// <node>
    /// 
    /// </node>
    /// <summary>
    /// Missing description
    /// </summary>
    [OriginalName("CUSTOMER_get")]
    public partial class CustomerGet : SimpleTaskModel<CustomerGetInput, CustomerGetOutput>
    {
    }
}