// <autogenerated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
using ConductorSharp.Engine.Model;
using ConductorSharp.Engine.Util;
using MediatR;
using Newtonsoft.Json;
using ConductorSharp.Engine.Builders;

namespace ConductorSharp.ScaffoldedDefinitions.Tasks
{
    public partial class EmailPrepareInput : IRequest<EmailPrepareOutput>
    {
        /// <originalName>
        /// customer_name
        /// </originalName>
        [JsonProperty("customer_name")]
        public dynamic CustomerName { get; set; }

        /// <originalName>
        /// address
        /// </originalName>
        [JsonProperty("address")]
        public dynamic Address { get; set; }
    }

    public partial class EmailPrepareOutput
    {
        /// <originalName>
        /// email_body
        /// </originalName>
        [JsonProperty("email_body")]
        public dynamic EmailBody { get; set; }
    }

    /// <originalName>
    /// EMAIL_prepare
    /// </originalName>
    /// <ownerEmail>
    /// undefined@undefined.local
    /// </ownerEmail>
    /// <node>
    /// 
    /// </node>
    /// <summary>
    /// Missing description
    /// </summary>
    [OriginalName("EMAIL_prepare")]
    public partial class EmailPrepare : SimpleTaskModel<EmailPrepareInput, EmailPrepareOutput>
    {
    }
}