name: Action test

on:
  push:
    tags: ["v1.*"]
    branches: [action_test]

jobs:
  deploy-packages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test ConductorSharp.sln