name: Action test

on:
  push:
    tags: ["v1.*"]

jobs:
  deploy-packages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Create package
      run: dotnet pack ./src/ConductorSharp.Engine -c Release
    - name: Publish package
      run: dotnet nuget push ./src/ConductorSharp.Engine/bin/Release/ConductorSharp.Engine*.nupkg --api-key {{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json